sudo: required

language: java

jdk:
  - openjdk8

before_install:
- sudo add-apt-repository ppa:cwchien/gradle -y
- sudo apt-get update -q
- sudo apt-get install gradle -y
- export PATH=/usr/bin:$PATH  # Use gradle from /usr/bin
- gradle --version

notifications:
  irc:
    channels:
      - "chat.freenode.net#vectorgraphics2d"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

after_success:
- gradle cobertura coveralls
